### ISSUE TITLE
Missing files for MCGA build

### ISSUE THREAD

**Issue by NY00123** [FrenkelS/keensource456tandy#16]
I think that an MCGA project file, and other possible files, are currently missing.

**Comment by NY00123** [comment]
On a second thought, the MCGA exe is re-using the Tandy data. So my guess is that it's just a matter of defining the macro MCGA in `KEEN4T/ID_HEADS.H`, but this can be checked later.

**Comment by FrenkelS** [comment]
Yeah, right now you need to enable this line https://github.com/FrenkelS/keensource456tandy/blob/main/KEEN4-6/KEEN4T/ID_HEADS.H#L68

But it would be more clear if I made a separate project file.

**Comment by FrenkelS** [comment]
I've added KEEN4M.PRJ

**Comment by NY00123** [comment]
Seems to be usable, thanks!
